In [10]:
import pandas as pd
from IPython.display import display

# Concatenate

In [36]:
# Combine two DataFrames row-wise (default axis=0)
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
print("Before:")
print(df1, "\n")
print(df2)
print("Combining two DataFrames row-wise:")
concat_df = pd.concat([df1, df2], ignore_index=True)
print(concat_df, "\n")
print("Concatenate along columns (axis=1)")
result = pd.concat([df1, df2], axis=1)
print(result)

Before:
   A  B
0  1  3
1  2  4

   A  B
0  5  7
1  6  8
Combining two DataFrames row-wise:
   A  B
0  1  3
1  2  4
2  5  7
3  6  8

Concatenate along columns (axis=1)
   A  B  A  B
0  1  3  5  7
1  2  4  6  8

In [ ]:
df3 = pd.DataFrame({'A': [9, 10], 'C': [11, 12]})

# Concatenate DataFrames with different columns
print(df1)
print(df3)
result = pd.concat([df1, df3], axis=0)
print(result)

   A  B
0  1  3
1  2  4
    A   C
0   9  11
1  10  12
   A  B   A   C
0  1  3   9  11
1  2  4  10  12

# Merge

In [19]:
# Merge on a shared column 'key'
df1 = pd.DataFrame({'key': ['A', 'B'], 'value': [1, 2]})
df2 = pd.DataFrame({'key': ['A', 'B'], 'value': [3, 4]})
print("Merging on shared column 'key':")
print("Before:")
print(df1)
print(df2)
merged_df = pd.merge(df1, df2, on='key')
print("After:")
print(merged_df, "\n")

Merging on shared column 'key':
Before:
  key  value
0   A      1
1   B      2
  key  value
0   A      3
1   B      4
After:
  key  value_x  value_y
0   A        1        3
1   B        2        4

In [22]:
# Merge on shared key
df_12 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'key': [1, 2, 3]})
df_13 = pd.DataFrame({'A': [7, 8, 9,10], 'B': [10, 11, 12,11], 'key': [1, 2, 3,4]})
print("Merging on shared 'key' column:"
    "\nBefore:")
print(df_12,"\n")
print(df_13, "\n")
print(pd.merge(df_12, df_13, on='key', how='inner'), "\n")

Merging on shared 'key' column:
Before:
   A  B  key
0  1  4    1
1  2  5    2
2  3  6    3

    A   B  key
0   7  10    1
1   8  11    2
2   9  12    3
3  10  11    4

   A_x  B_x  key  A_y  B_y
0    1    4    1    7   10
1    2    5    2    8   11
2    3    6    3    9   12

In [21]:
# Merge on 'city'
df1 = pd.DataFrame({"city": ["new york", "chicago", "orlando"], "temperature": [21, 14, 35]})
df2 = pd.DataFrame({"city": ["chicago", "new york", "orlando"], "humidity": [65, 68, 75]})
print("Merging on column 'city':")
print("Before:")
print(df1)
print(df2)
merged = pd.merge(df1, df2, on="city")
print("After:")
print(merged, "\n")

Merging on column 'city':
Before:
       city  temperature
0  new york           21
1   chicago           14
2   orlando           35
       city  humidity
0   chicago        65
1  new york        68
2   orlando        75
After:
       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:


# Merge with indicator
print("Merge with indicator column:")
df1 = pd.DataFrame({"city": ["new york", "chicago", "orlando"], "temperature": [21, 14, 35]})
df2 = pd.DataFrame({"city": ["chicago", "new york", "orlando"], "humidity": [65, 68, 75]})
print("Merging on column 'city':")
print("Before:")
print(df1)
print(df2)
print(pd.merge(df1, df2, on="city", how="outer", indicator=True), "\n")

# Merge with suffixes
df1 = pd.DataFrame({
    "city": ["new york", "chicago", "orlando", "baltimore"],
    "temperature": [21, 14, 35, 38],
    "humidity": [65, 68, 71, 75]
})
df2 = pd.DataFrame({
    "city": ["chicago", "new york", "san diego"],
    "temperature": [21, 14, 35],
    "humidity": [65, 68, 71]
})
print("Merge with custom suffixes for overlapping columns:")
print(pd.merge(df1, df2, on="city", how="outer", suffixes=('_first', '_second')), "\n")

### SQL-style joins

In [ ]:
df1 = pd.DataFrame({"city": ["new york", "chicago", "orlando", "baltimore"], "temperature": [21, 14, 35, 38]})
df2 = pd.DataFrame({"city": ["chicago", "new york", "san diego"], "humidity": [65, 68, 71]})
print(df1)
print(df2)

        city  temperature
0   new york           21
1    chicago           14
2    orlando           35
3  baltimore           38
        city  humidity
0    chicago        65
1   new york        68
2  san diego        71

In [25]:
print("Inner join on 'city':")
print(pd.merge(df1, df2, on="city", how="inner"), "\n")

Inner join on 'city':
       city  temperature  humidity
0  new york           21        68
1   chicago           14        65

In [ ]:
print("Outer join on 'city':")
print(pd.merge(df1, df2, on="city", how="outer"), "\n")

Outer join on 'city':
        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         14.0      65.0
2   new york         21.0      68.0
3    orlando         35.0       NaN
4  san diego          NaN      71.0

In [27]:
print("Left join on 'city':")
print(pd.merge(df1, df2, on="city", how="left"), "\n")

Left join on 'city':
        city  temperature  humidity
0   new york           21      68.0
1    chicago           14      65.0
2    orlando           35       NaN
3  baltimore           38       NaN

In [28]:
print("Right join on 'city':")
print(pd.merge(df1, df2, on="city", how="right"), "\n")

Right join on 'city':
        city  temperature  humidity
0    chicago         14.0        65
1   new york         21.0        68
2  san diego          NaN        71

# Join

In [29]:
df1 = pd.DataFrame({'val1': [1, 2]}, index=['A', 'B'])
df2 = pd.DataFrame({'val2': [3, 4]}, index=['A', 'B'])
print(df1)
print(df2)
# Join on index
df1.join(df2)

   val1
A     1
B     2
   val2
A     3
B     4

   val1  val2
A     1     3
B     2     4

In [30]:
### 3. `.join()` with `on=` joins index with a column of another DataFrame
df1 = pd.DataFrame({'val1': [1, 2]}, index=['A', 'B'])
df2 = pd.DataFrame({'key': ['A', 'B'], 'val2': [3, 4]})
print(df1)
print(df2)
df1.join(df2.set_index('key'), on=df1.index)

   val1
A     1
B     2
  key  val2
0   A     3
1   B     4

  key_0  val1  val2
A     A     1     3
B     B     2     4

In [31]:
# Join two DataFrames using their index
df1 = pd.DataFrame({'key': ['A', 'B'], 'val1': [1, 2]}).set_index('key')
df2 = pd.DataFrame({'key': ['A', 'B'], 'val2': [3, 4]}).set_index('key')
print("Joining two DataFrames on their index:")
print("Before:")
print(df1)
print(df2)
joined_df = df1.join(df2, lsuffix='_left', rsuffix='_right')
print("After:")
print(joined_df, "\n")

Joining two DataFrames on their index:
Before:
     val1
key
A       1
B       2
     val2
key
A       3
B       4
After:
     val1  val2
key
A       1     3
B       2     4

In [33]:
# Join on index
df1 = pd.DataFrame({"city": ["new york", "chicago", "orlando"], "temperature": [21, 14, 35]}).set_index('city')
df2 = pd.DataFrame({"city": ["chicago", "new york", "orlando"], "humidity": [65, 68, 75]}).set_index('city')
print(df1)
print(df2)
print("\n Joining on index after setting 'city' as index:")
print(df1.join(df2, lsuffix='_l', rsuffix='_r'), "\n")

          temperature
city
new york           21
chicago            14
orlando            35
          humidity
city
chicago         65
new york        68
orlando         75

 Joining on index after setting 'city' as index:
          temperature  humidity
city
new york           21        68
chicago            14        65
orlando            35        75

In [34]:
# Join with different indexes
df_12 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]}, index=[1, 2, 3])
df_13 = pd.DataFrame({'C': [7, 8, 9], 'D': [10, 11, 12]}, index=[1, 4, 5])
print(df_12)
print(df_13)
print("Joining DataFrames with partially overlapping indices:")
print(df_12.join(df_13, how='outer'), "\n")

   A  B
1  1  4
2  2  5
3  3  6
   C   D
1  7  10
4  8  11
5  9  12
Joining DataFrames with partially overlapping indices:
     A    B    C     D
1  1.0  4.0  7.0  10.0
2  2.0  5.0  NaN   NaN
3  3.0  6.0  NaN   NaN
4  NaN  NaN  8.0  11.0
5  NaN  NaN  9.0  12.0